//
//  ServerURL.swift
//  TMLBaseTemplateMVVM
//
//  Created by Apple on 14/02/19.
//  Copyright © 2019 Apple. All rights reserved.
//
import Foundation
// MARK: PROD ENVIRONMENT SERVER URL KEYS
#if PROD
//print("Prod Case with ssl")
internal let BASEURL = "https://az.thebeerconnect.com/wp-json/mobiconnect/"
internal let HEADERKEY = "thebeerconnectaz"

internal let LOGINURL = BASEURL+"customer_account/login"
internal let SEARCHURL = BASEURL+"getsearchedproducts"
internal let FETCHUSERPROFILE = BASEURL+"customer_account/fetch_userprofile"
internal let UPDATEPROFILE = BASEURL+"customer_account/updateProfile"
internal let DASHBOARDURL = BASEURL+"get_homepage_details"
internal let CATEGORYURL = BASEURL+"get_all_cat_products"
internal let PRODUCTDETAILS = BASEURL+"get_single_product"
internal let SETWISHLIST = BASEURL+"set_user_wishlist"
internal let FETCHWISHLIST = BASEURL+"fetch_user_wishlist"
internal let ADDTOCART = BASEURL+"checkout/addtocart"
internal let VIEWCART = BASEURL+"checkout/viewcart"
internal let UPDATECART = BASEURL+"checkout/updatecart"
internal let REMOVEITEM = BASEURL+"checkout/removecart"
internal let DELETECART = BASEURL+"checkout/deletecart"
internal let CARTCOUNT = BASEURL+"customer_account/getcartcount"
internal let ADDRESSHIPPING = BASEURL+"checkout/getsavedaddress"
internal let SAVEADDRESS = BASEURL+"checkout/saveuseraddress"
internal let ORDERCHECKOUT = BASEURL+"checkout/checkoutdetailpage"
internal let PROCESSCHECKOUT = BASEURL+"checkout/processcheckout"
internal let TIMESLOTS = BASEURL+"checkout/getalottimeslots"
internal let APPLAUNCH = BASEURL+"get_launch_settings"
internal let SEARCHEDPRODUCT = BASEURL+"getsearchedproducts"
internal let ORDERPRODUCTLIST = BASEURL+"fetch_user_orderslist"
internal let ORDERPRODUCTDETAIL = BASEURL+"fetch_user_ordersdetails"
internal let ORDEREMAILDOWNLOAD = BASEURL+"order/download_invoice"
internal let ADMINCUSTOMERLIST = BASEURL+"customer_account/getcustomerlist"
internal let FILTERCAT = BASEURL+"gettopfiltercategory"
internal let FORGOTPASS = BASEURL+"customer_account/forgotPassword"
internal let GETCUSTOMERLOGIN = BASEURL+"getcustomerlogin"
internal let SAVETOKENID = BASEURL+"customer_account/savetokenid"
internal let REMOVETOKENID = BASEURL+"customer_account/removetokenid"
internal let GETNOTIFICATION = BASEURL+"customer_account/notificationcenter"
internal let SIGNUPWEBURL = "https://thebeerconnect.typeform.com/to/UbNpp7"

#else
//email=raveena.synsoft&password=Raveena1234
//internal let BASEURL = "https://woocommerce-132018-927252.cloudwaysapps.com/wp-json/mobiconnect/"
internal let BASEURL = "http://testing.thebeerconnect.com/wp-json/mobiconnect/"
internal let HEADERKEY = "thebeerconnectaz"
//internal let BASEURL = "http://192.168.0.211/wp-reporting/wp-json/mobiconnect/"
//internal let BASEURL = "http://192.168.0.42/wordpress-reporting/wp-json/mobiconnect/"
// internal let HEADERKEY = "mobiconnect123"
internal let LOGINURL = BASEURL+"customer_account/login"
internal let SEARCHURL = BASEURL+"getsearchedproducts"
internal let FETCHUSERPROFILE = BASEURL+"customer_account/fetch_userprofile"
internal let UPDATEPROFILE = BASEURL+"customer_account/updateProfile"
internal let DASHBOARDURL = BASEURL+"get_homepage_details"
internal let CATEGORYURL = BASEURL+"get_all_cat_products"
internal let PRODUCTDETAILS = BASEURL+"get_single_product"
internal let SETWISHLIST = BASEURL+"set_user_wishlist"
internal let FETCHWISHLIST = BASEURL+"fetch_user_wishlist"
internal let ADDTOCART = BASEURL+"checkout/addtocart"
internal let VIEWCART = BASEURL+"checkout/viewcart"
internal let UPDATECART = BASEURL+"checkout/updatecart"
internal let REMOVEITEM = BASEURL+"checkout/removecart"
internal let DELETECART = BASEURL+"checkout/deletecart"
internal let CARTCOUNT = BASEURL+"customer_account/getcartcount"
internal let ADDRESSHIPPING = BASEURL+"checkout/getsavedaddress"
internal let SAVEADDRESS = BASEURL+"checkout/saveuseraddress"
internal let ORDERCHECKOUT = BASEURL+"checkout/checkoutdetailpage"
internal let PROCESSCHECKOUT = BASEURL+"checkout/processcheckout"
internal let TIMESLOTS = BASEURL+"checkout/getalottimeslots"
internal let APPLAUNCH = BASEURL+"get_launch_settings"
internal let SEARCHEDPRODUCT = BASEURL+"getsearchedproducts"
internal let ORDERPRODUCTLIST = BASEURL+"fetch_user_orderslist_v2"
internal let ORDERPRODUCTDETAIL = BASEURL+"fetch_user_ordersdetails"
internal let ORDEREMAILDOWNLOAD = BASEURL+"order/download_invoice"
internal let ADMINCUSTOMERLIST = BASEURL+"customer_account/getcustomerlist"
internal let FILTERCAT = BASEURL+"gettopfiltercategory"
internal let FORGOTPASS = BASEURL+"customer_account/forgotPassword"
internal let GETCUSTOMERLOGIN = BASEURL+"customer_account/getcustomerlogin"
internal let SAVETOKENID = BASEURL+"customer_account/savetokenid"
internal let REMOVETOKENID = BASEURL+"customer_account/removetokenid"
internal let GETNOTIFICATION = BASEURL+"customer_account/notificationcenter"
internal let SIGNUPWEBURL = "https://www.youtube.com/embed/tgbNymZ7vqY?playlist=tgbNymZ7vqY&loop=1"//"https://thebeerconnect.typeform.com/to/UbNpp7"
#endif
